[package]
name = "spybeep"
description = "Make your keyboard beep 🤖🤖🤖"
version = "0.3.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/p6nj/spybeep"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
freqiterator = "2.0"
mki = "0.2"
rodio = { version = "0.17", default-features = false }
