[package]
name = "spybeep"
description = "Make your keyboard beep 🤖🤖🤖"
version = "0.1.0"
edition = "2021"
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freqiterator = "0.1.0"
mki = "0.2.3"
rodio = { version = "0.17.3", default-features = false }
